"""Added company and name to user

Revision ID: 77ef3f76a9f1
Revises: bb0efdb5663c
Create Date: 2024-01-30 15:26:26.674501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ef3f76a9f1'
down_revision = 'bb0efdb5663c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('company')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
